### ISSUE TITLE
which path for extension packages?

### ISSUE THREAD

**Issue by ethoms-usgs** [Esri/raster-functions#26]
When I run 'python setup.py install' to install the extensions, do I want 
C:\Python27\ArcGIS10.3\python.exe or
C:\Python27\ArcGISx6410.3\python.exe
in my path variable?

**Comment by jdrisdelle** [comment]
Potentially both. If you are planning on using these scripts in desktop only then you will have to run C:\Python27\ArcGIS10.3\python.exe. If you are going to be using them with image services then you will need to use C:\Python27\ArcGISx6410.3\python.exe.

**Comment by evanthoms** [comment]
Ok!  thanks for the prompt reply.
