### ISSUE TITLE
Elevation Fill Void - Fill raster function

### ISSUE THREAD

**Issue by ellend999** [Esri/raster-functions#38]
I am looking at using the Elevation Fill Void function (I believe it is called Fill Raster under the function folder) as an alternative to the Spatial Analyst Fill function.  When I run the function in ArcGIS Pro, the result  I get are not what I expect and analysis run on the result of the raster function are incorrect. 
I looked at the code under the function folder here.  There is no inline documentation in the code. I am having trouble following what it does and how it relates the raster tool in ArcGIS Pro.
1) Is the fill raster function code the code for the Elevation Fill Void?  If not can you please point me to the code for that function?
2) If it is the code can you please provide additional information so I can understand exactly what the code is supposed to be doing.
3) Is there a way to directly access the function code from ArcGIS Pro?
Thank you.

**Comment by jdrisdelle** [comment]
Hi Ellen,

1.  No the fill raster code is a code sample that a user committed to our Git Hub repo.  It much simpler that the elevation void fill tool.  It essentially populates an array with a user defined value.  In this case it fills the entire raster with that value.  The code being used is a numpy function:

pixelBlocks['output_pixels'] = np.full(shape, self.fillValue, dtype=props['pixelType'])

We don't document these as they are code samples uploaded from our users.  It is up to them to document/comment their code.  

There is a function that is available out-of-the-box that does what you want. 

http://pro.arcgis.com/en/pro-app/help/data/imagery/elevation-void-fill-function.htm

2.  I'm not sure if i can send you the code for the out-of-the -box function as it is is proprietary. 

3.  You can open the code from any text editor or Python IDE.

**Comment by ellend999** [comment]
Thanks for the quick response.  I was using the elevation void fill function within ArcGIS Pro but it is not performing as expected.  It is leaving cells unfilled that should be filled.  
If I actually had the code, I understand I can open it in any text editor, but from what you are saying, I cannot access the code for the elevation-void-fill-function because its proprietary - yes?
Is there a way to call the function directly from python? I understand it is NOT part of ArcPy.

**Comment by jdrisdelle** [comment]
it can't really be called from Python. We do have a generate raster gp tool that will consume a raster+ function template a generate a physical output raster.  You can place the void fill function in the template and use it.  If you are using the out-of-the-box function and it is not working we can investigate that. What are you setting as your max void width? Can you share the raster?

**Comment by ellend999** [comment]
The raster is just a selected HUC6 from the 10M NED available from the USGS.  
I left the Max Void width to the default 0 so that all voids were to be filled.
I am running code but can share the raster when the data is free.

**Comment by jdrisdelle** [comment]
Ok.  I can take a look at it and see what is causing the problem.  The developer that worked on that tool is just down the hall.  I can have him take a look at it.   Are the holes that are not being filled doughnut holes or are they on the edge of your data?

**Comment by jdrisdelle** [comment]
Hi @ellend999,  

Do you still want me to take a look at your data?

**Comment by ellend999** [comment]
I had a family emergency I will get back to you tomorrow.

**Comment by ellend999** [comment]
I noticed the issue when I went on to produce flow direction grids from the fill grid produced by the raster function.  The flow direction grids produced values that are not legitimate flow direction values (in other words not 1,2,4,8,16,32,64, or 128.  This happens when there are sinks in the data.   When I run the Spatial Analyst/Fill tool and then run the flow direction, the flow direction values were all appropriate.  I tried attaching the dem I was using but it was too big.  Let me know if you have an alternative way for me to get you the data.

**Comment by jdrisdelle** [comment]
@ellend999.  I just took  a closer look at the fill gp tool and the elevation fill  function.  They are actually doing different things.  The elevation void fill function actually fills nodata values in your DEM using either a fitted plane or idw interpolation.  This was deigned to fill in holes created in Lidar derived DEMs caused in bare earth DTMs (i.e. building footprints or lakes).  

The fill gp tool actually fills **sinks** which are hydrological anomalies in DEMs and not just holes from missing data. 

So these two tools do different things at the end of the day. Maybe we can try to make a Python raster function that does something similar to the fill gp tool. Try plugging this function into the Python raster fucntion and see what it does:

https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.ndimage.morphology.binary_fill_holes.html

Use the fill function from our repo as a starting point. Replace the current function in the updatepixels() method with this one.  I can help if you get stuck.

**Comment by ellend999** [comment]
Ahh ok that makes sense with the results I was getting. Thanks for looking at this. I will take a look at the raster function you suggested.
