### ISSUE TITLE
aspect-slope raster function problems

### ISSUE THREAD

**Issue by greatzzk** [Esri/raster-functions#40]
From Cristelle:
Bug 1: White Patches/Areas appear at zoomed out levels, on application of Aspect-Slope Raster Function on a “Mosaic Dataset” in ArcMap
Version tested on: 10.5

Data Location :   \\spider\Swap\Cristelle\Zikang\Aspect_Slope\ArcMap\WhiteAreas_Mosaic 

-	From ArcCatalog, access “Mosaic”  ->Right-click “Properties” -> Processing Templates -> “+” -> Right- Click on “identity function” -> Insert Python Raster function -> Add AspectSlope.py to the Python module parameter -> OK-> Apply
-	Now Add the Mosaic to Table of contents -> Layer Properties -> Processing Templates -> Select the newly added Python raster function -> Apply
-	Notice the White spots/areas present at zoomed out levels only
-	Issue not reproducible on Raster Dataset or Image service. Reproducible only on Mosaic Datasets.

Bug 2: Only Pixel borders appear colorized, below scale levels of 20000, on application of Aspect-Slope Raster Function on an Image Service in ArcMap
Version tested on: 10.5

Data Location :  https://elevation.arcgis.com/arcgis/rest/services/WorldElevation/Terrain/ImageServer 
                                \\spider\Swap\Cristelle\Zikang\Aspect_Slope\ArcMap\PixelBorders_Service 
                   

-	From ArcCatalog, add ArcGIS Server connection to https://elevation.arcgis.com/arcgis/rest/services/WorldElevation/Terrain/ImageServer (You may need to be logged into AGOL within ArcMap in order to access this elevation service)
-	Add the Terrain service to ArcMap
-	From ArcMap “Windows” option -> Image Analysis  -> Select layer -> Add function -> Right- Click on “identity function” -> Insert Python Raster function -> Add AspectSlope.py to the Python module parameter -> OK
-	Now zoom into the Function Layer. Notice at zoomed out levels the colomap appears fine, however below scales of about 20,000 only the pixel borders appear to be colorized
-	Issue not reproducible on Raster Dataset or Mosaic Datasets. Reproducible only on Image service.

Bug 3: Legend/Colormap doesn’t get applied , on application of Aspect-Slope Raster Function on a Raster Dataset, Mosaic or Image Service in ArcGIS Pro
Version tested on: ArcGIS Pro 1.4

Data Location :  \\spider\Swap\Cristelle\Zikang\Aspect_Slope\Pro\NoColorMap     
                                https://elevation.arcgis.com/arcgis/rest/services/WorldElevation/Terrain/ImageServer

-	Copy over AspectSlope.py to C:\Program Files\ArcGIS\Pro\Resources\Raster\Functions\Custom\AspectSlope 
-	From ArcGIS Pro, view either “SETSM_WV01_20130312_1020010021857100_102001002012D800_seg1_8m_dem.tif”, “Mosaic” or Image service “ https://elevation.arcgis.com/arcgis/rest/services/WorldElevation/Terrain/ImageServer”
-	From Ribbon -> Imagery -> Function Editor -> Add the Raster Dataset and AspectSlope.py into the editor and link them & save it as a AspectSlope.rft
-	From Raster Functions Tab -> Custom -> AspectSlope.rft -> Select input -> Create new layer
-	Notice the Legend is white and data does not display. If you use the identify tool the Pixel Values show up.
-	Issue not reproducible in ArcMap. Reproducible only in ArcGIS Pro.

**Comment by jdrisdelle** [comment]
These should all be fixed in Pro 2.2 @greatzzk .
