### ISSUE TITLE
can not import scikit-image in ArcGIS Pro 1.4

### ISSUE THREAD

**Issue by ricrockstar** [Esri/raster-functions#42]
I'm using ArcGIS Pro 1.4 and want to create my own raster functions with scikit-image. ArcGIS Pro 1.4 is using python 3.5. I downloaded every library from this page in version 3.5 and have it installed, but it is not working.
http://www.lfd.uci.edu/~gohlke/pythonlibs/#cython
Has somebody any idea what my fault is or maybe it's not working with python 3.5?

**Comment by jdrisdelle** [comment]
Let me look into that @ricrockstar . We did change the Python implementation/install path slightly at 1.4.  Take a look under "Project tab > Python" and make sure Scikit image is in that list.

**Comment by ricrockstar** [comment]
I have looked in ArcGIS Pro 1.4 under project, but it is not present. If I look on my PC under the ArcGIS Pro path, where I installed the scikit-image package, it shows up. Is there an solution to get it into ArcGIS Pro 1.4?

**Comment by jdrisdelle** [comment]
@ricrockstar Try selecting **add packages** then search for **scikit image**. Try installing it from here. It should install and path to everything for you.

**Comment by ricrockstar** [comment]
Thanks a lot, now it works
