### ISSUE TITLE
How to use code

### ISSUE THREAD

**Issue by Kafajo** [Esri/raster-functions#46]
Hello

I'm not used to use python scripts. How would I implement the code into my ArcMap project?
If I try to generate a new toolbox the script gives no error but also does not produce any output...

Thanks!

**Comment by jgravois** [comment]
have you reviewed the steps for [Getting Started](https://github.com/Esri/raster-functions#getting-started) that are outlined in the README?

**Comment by jdrisdelle** [comment]
@Kafajo Here are the help docs for [Pro](http://pro.arcgis.com/en/pro-app/help/data/imagery/python-raster-function-deployment.htm) and [10.6](http://desktop.arcgis.com/en/arcmap/latest/manage-data/raster-and-images/python-raster-function.htm).  Long story short-it can be found in the options menu of the raster function panein Pro:
![image](https://user-images.githubusercontent.com/8249074/36042474-cdbc57f6-0d80-11e8-9afa-3af8808771f8.png)

Or in ArcMap by selecting  a raster in the image analysis window then clicking on the f(x) button. When the function dilaog opens, right click in the raster in the function chain then select **Insert Python Raster Function**.

![image](https://user-images.githubusercontent.com/8249074/36042770-c684195a-0d81-11e8-96ee-0cbf926be23f.png)

Hope this helps.

**Comment by Kafajo** [comment]
Hi John,

 

Sorry, no I haven’t. Now it’s working! Thanks :)

 

Jonas
