### ISSUE TITLE
Write Wiki to have instructions for ArcGIS Pro instead or in addition to ArcMap

### ISSUE THREAD

**Issue by gbrunner** [Esri/raster-functions#47]
@jdrisdelle I think the Wiki should reference how to do this in ArcGIS Pro. That's what I am using and some other people that I work with are using. Also, we submit RA jobs from ArcGIS Pro, so it would be beneficial to have the instructions written from ArcGIS Pro.

**Comment by jdrisdelle** [comment]
I will update the wiki @gbrunner

**Comment by jdrisdelle** [comment]
Added a section to the wiki for using python raster function in Pro.
