### ISSUE TITLE
Deploy Raster function on server

### ISSUE THREAD

**Issue by resnow0892** [Esri/raster-functions#80]
Hello, 

I successfully managed to develop a small python raster function. I created a new custom category in `C:\Program Files\ArcGIS\Pro\Resources\Raster\Functions\Custom\` and in ` C:\Program Files\ArcGIS\Server\framework\runtime\ArcGIS\Resources\Raster\Functions\Custom\`

I copied the python script and the xml raster function in these two folders. it should be possible to use my python raster function on the server and arcgis Online. It works on Arcgis pro on the server but, impossible to to apply the function on mosaic service on Arcgis Online.

Thanks for your help.

**Comment by shenganzhan** [comment]
Did you change the reference to the python script?

> Reference python scripts using the ‘well known home folder’. This requires the developer to reference Python scripts using the following syntax in the associated rft: [functions]Custom\custom1\script.py

**Comment by resnow0892** [comment]
Yes it is referenced in the xml file as `<AnyType xsi:type="xs:string">[functions]Custom\RFT_python\RFT_Python.py</AnyType>`

**Comment by shenganzhan** [comment]
Try to narrow it down a bit (i.e. use a simple operation in the python script). Also make sure you restart arcgis server after copying the rft and script

**Comment by resnow0892** [comment]
it worked, the issue was on something else. Thanks for your help.
